### ISSUE TITLE
[Feature Request] 增加剩余流量和到期时间

### ISSUE THREAD

**Issue by amokiel** [Yos-X/ClashYou#2]
### 功能描述

在配置页面醒目显示剩余流量和到期时间。这样的话，应该会方便很多。

**Comment by Yos-X** [comment]
在之后的版本可能会添加**通过代理运营商获取**的流量信息。
关于为什么不是实时流量，请参见原作者的回复。
![Screenshot_2023-07-27-20-47-33-919_mark via-edit](https://github.com/Yos-X/ClashYou/assets/97019070/7674d04d-9de1-4099-9e1a-1b6d97615ab5)

**Comment by Yos-X** [comment]
0.1.1版本已添加，预发布
